//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/michiel/TabletopWitch/src/PreProcess/micfort.GMDroid.PF/Monster/PF.g4 by ANTLR 4.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IPFListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.3")]
[System.CLSCompliant(false)]
public partial class PFBaseListener : IPFListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.gearCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGearCell([NotNull] PFParser.GearCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.gearCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGearCell([NotNull] PFParser.GearCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.skills"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSkills([NotNull] PFParser.SkillsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.skills"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSkills([NotNull] PFParser.SkillsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.skillName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSkillName([NotNull] PFParser.SkillNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.skillName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSkillName([NotNull] PFParser.SkillNameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.restistList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRestistList([NotNull] PFParser.RestistListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.restistList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRestistList([NotNull] PFParser.RestistListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.vulnerabilityCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVulnerabilityCell([NotNull] PFParser.VulnerabilityCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.vulnerabilityCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVulnerabilityCell([NotNull] PFParser.VulnerabilityCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.reachCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReachCell([NotNull] PFParser.ReachCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.reachCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReachCell([NotNull] PFParser.ReachCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.immuneCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImmuneCell([NotNull] PFParser.ImmuneCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.immuneCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImmuneCell([NotNull] PFParser.ImmuneCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.characterflagCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCharacterflagCell([NotNull] PFParser.CharacterflagCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.characterflagCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCharacterflagCell([NotNull] PFParser.CharacterflagCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.alignmentCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAlignmentCell([NotNull] PFParser.AlignmentCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.alignmentCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAlignmentCell([NotNull] PFParser.AlignmentCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.ac_modsCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAc_modsCell([NotNull] PFParser.Ac_modsCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.ac_modsCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAc_modsCell([NotNull] PFParser.Ac_modsCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.spellspreparedCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpellspreparedCell([NotNull] PFParser.SpellspreparedCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.spellspreparedCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpellspreparedCell([NotNull] PFParser.SpellspreparedCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.mrCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMrCell([NotNull] PFParser.MrCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.mrCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMrCell([NotNull] PFParser.MrCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.othergearCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOthergearCell([NotNull] PFParser.OthergearCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.othergearCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOthergearCell([NotNull] PFParser.OthergearCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.diceCount"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDiceCount([NotNull] PFParser.DiceCountContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.diceCount"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDiceCount([NotNull] PFParser.DiceCountContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.traitsCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTraitsCell([NotNull] PFParser.TraitsCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.traitsCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTraitsCell([NotNull] PFParser.TraitsCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.srCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSrCell([NotNull] PFParser.SrCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.srCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSrCell([NotNull] PFParser.SrCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.treasureCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTreasureCell([NotNull] PFParser.TreasureCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.treasureCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTreasureCell([NotNull] PFParser.TreasureCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.nameCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNameCell([NotNull] PFParser.NameCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.nameCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNameCell([NotNull] PFParser.NameCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.armorClass"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArmorClass([NotNull] PFParser.ArmorClassContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.armorClass"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArmorClass([NotNull] PFParser.ArmorClassContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.monster"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMonster([NotNull] PFParser.MonsterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.monster"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMonster([NotNull] PFParser.MonsterContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.defensiveabilitiesCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefensiveabilitiesCell([NotNull] PFParser.DefensiveabilitiesCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.defensiveabilitiesCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefensiveabilitiesCell([NotNull] PFParser.DefensiveabilitiesCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.hp_modsCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHp_modsCell([NotNull] PFParser.Hp_modsCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.hp_modsCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHp_modsCell([NotNull] PFParser.Hp_modsCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.cell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCell([NotNull] PFParser.CellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.cell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCell([NotNull] PFParser.CellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.hd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHd([NotNull] PFParser.HdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.hd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHd([NotNull] PFParser.HdContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.weaknessesCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWeaknessesCell([NotNull] PFParser.WeaknessesCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.weaknessesCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWeaknessesCell([NotNull] PFParser.WeaknessesCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.drCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDrCell([NotNull] PFParser.DrCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.drCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDrCell([NotNull] PFParser.DrCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.sourceCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSourceCell([NotNull] PFParser.SourceCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.sourceCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSourceCell([NotNull] PFParser.SourceCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHeader([NotNull] PFParser.HeaderContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHeader([NotNull] PFParser.HeaderContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.spellsknownCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpellsknownCell([NotNull] PFParser.SpellsknownCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.spellsknownCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpellsknownCell([NotNull] PFParser.SpellsknownCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.crCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCrCell([NotNull] PFParser.CrCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.crCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCrCell([NotNull] PFParser.CrCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.pf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPf([NotNull] PFParser.PfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.pf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPf([NotNull] PFParser.PfContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.skill"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSkill([NotNull] PFParser.SkillContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.skill"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSkill([NotNull] PFParser.SkillContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.savesRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSavesRef([NotNull] PFParser.SavesRefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.savesRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSavesRef([NotNull] PFParser.SavesRefContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.companionflagCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompanionflagCell([NotNull] PFParser.CompanionflagCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.companionflagCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompanionflagCell([NotNull] PFParser.CompanionflagCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.sensesCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSensesCell([NotNull] PFParser.SensesCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.sensesCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSensesCell([NotNull] PFParser.SensesCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.focusedschoolCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFocusedschoolCell([NotNull] PFParser.FocusedschoolCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.focusedschoolCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFocusedschoolCell([NotNull] PFParser.FocusedschoolCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.swimCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwimCell([NotNull] PFParser.SwimCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.swimCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwimCell([NotNull] PFParser.SwimCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.senses"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSenses([NotNull] PFParser.SensesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.senses"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSenses([NotNull] PFParser.SensesContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.speed_modCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpeed_modCell([NotNull] PFParser.Speed_modCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.speed_modCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpeed_modCell([NotNull] PFParser.Speed_modCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.ac_modSpecial"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAc_modSpecial([NotNull] PFParser.Ac_modSpecialContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.ac_modSpecial"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAc_modSpecial([NotNull] PFParser.Ac_modSpecialContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLine([NotNull] PFParser.LineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLine([NotNull] PFParser.LineContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.bloodlineCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBloodlineCell([NotNull] PFParser.BloodlineCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.bloodlineCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBloodlineCell([NotNull] PFParser.BloodlineCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.basestatisticsCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBasestatisticsCell([NotNull] PFParser.BasestatisticsCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.basestatisticsCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBasestatisticsCell([NotNull] PFParser.BasestatisticsCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.distance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDistance([NotNull] PFParser.DistanceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.distance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDistance([NotNull] PFParser.DistanceContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.idCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdCell([NotNull] PFParser.IdCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.idCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdCell([NotNull] PFParser.IdCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.cmbCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmbCell([NotNull] PFParser.CmbCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.cmbCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmbCell([NotNull] PFParser.CmbCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.specialattacksCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecialattacksCell([NotNull] PFParser.SpecialattacksCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.specialattacksCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecialattacksCell([NotNull] PFParser.SpecialattacksCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.quotedText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuotedText([NotNull] PFParser.QuotedTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.quotedText"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuotedText([NotNull] PFParser.QuotedTextContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.linktextCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLinktextCell([NotNull] PFParser.LinktextCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.linktextCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLinktextCell([NotNull] PFParser.LinktextCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.duringcombatCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDuringcombatCell([NotNull] PFParser.DuringcombatCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.duringcombatCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDuringcombatCell([NotNull] PFParser.DuringcombatCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.hdCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHdCell([NotNull] PFParser.HdCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.hdCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHdCell([NotNull] PFParser.HdCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.spaceCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpaceCell([NotNull] PFParser.SpaceCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.spaceCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpaceCell([NotNull] PFParser.SpaceCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.companionfamiliarlinkCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompanionfamiliarlinkCell([NotNull] PFParser.CompanionfamiliarlinkCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.companionfamiliarlinkCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompanionfamiliarlinkCell([NotNull] PFParser.CompanionfamiliarlinkCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.mythicCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMythicCell([NotNull] PFParser.MythicCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.mythicCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMythicCell([NotNull] PFParser.MythicCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.ac_mod"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAc_mod([NotNull] PFParser.Ac_modContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.ac_mod"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAc_mod([NotNull] PFParser.Ac_modContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.dr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDr([NotNull] PFParser.DrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.dr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDr([NotNull] PFParser.DrContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.classarchetypesCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassarchetypesCell([NotNull] PFParser.ClassarchetypesCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.classarchetypesCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassarchetypesCell([NotNull] PFParser.ClassarchetypesCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.istemplateCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIstemplateCell([NotNull] PFParser.IstemplateCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.istemplateCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIstemplateCell([NotNull] PFParser.IstemplateCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.monstersourceCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMonstersourceCell([NotNull] PFParser.MonstersourceCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.monstersourceCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMonstersourceCell([NotNull] PFParser.MonstersourceCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.mysteryCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMysteryCell([NotNull] PFParser.MysteryCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.mysteryCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMysteryCell([NotNull] PFParser.MysteryCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.immune"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImmune([NotNull] PFParser.ImmuneContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.immune"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImmune([NotNull] PFParser.ImmuneContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.variantCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariantCell([NotNull] PFParser.VariantCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.variantCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariantCell([NotNull] PFParser.VariantCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.fulltextCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFulltextCell([NotNull] PFParser.FulltextCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.fulltextCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFulltextCell([NotNull] PFParser.FulltextCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.uniquemonsterCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUniquemonsterCell([NotNull] PFParser.UniquemonsterCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.uniquemonsterCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUniquemonsterCell([NotNull] PFParser.UniquemonsterCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.savesWill"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSavesWill([NotNull] PFParser.SavesWillContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.savesWill"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSavesWill([NotNull] PFParser.SavesWillContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.racialmodsCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRacialmodsCell([NotNull] PFParser.RacialmodsCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.racialmodsCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRacialmodsCell([NotNull] PFParser.RacialmodsCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.savesFort"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSavesFort([NotNull] PFParser.SavesFortContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.savesFort"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSavesFort([NotNull] PFParser.SavesFortContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.ac_mods"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAc_mods([NotNull] PFParser.Ac_modsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.ac_mods"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAc_mods([NotNull] PFParser.Ac_modsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.alternatenameformCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAlternatenameformCell([NotNull] PFParser.AlternatenameformCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.alternatenameformCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAlternatenameformCell([NotNull] PFParser.AlternatenameformCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.subtypeCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubtypeCell([NotNull] PFParser.SubtypeCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.subtypeCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubtypeCell([NotNull] PFParser.SubtypeCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.mtCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMtCell([NotNull] PFParser.MtCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.mtCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMtCell([NotNull] PFParser.MtCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.description_visualCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDescription_visualCell([NotNull] PFParser.Description_visualCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.description_visualCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDescription_visualCell([NotNull] PFParser.Description_visualCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.patronCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPatronCell([NotNull] PFParser.PatronCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.patronCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPatronCell([NotNull] PFParser.PatronCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.mclassName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMclassName([NotNull] PFParser.MclassNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.mclassName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMclassName([NotNull] PFParser.MclassNameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.moraleCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMoraleCell([NotNull] PFParser.MoraleCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.moraleCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMoraleCell([NotNull] PFParser.MoraleCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.savesCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSavesCell([NotNull] PFParser.SavesCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.savesCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSavesCell([NotNull] PFParser.SavesCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.sqCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSqCell([NotNull] PFParser.SqCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.sqCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSqCell([NotNull] PFParser.SqCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.mclassCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMclassCell([NotNull] PFParser.MclassCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.mclassCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMclassCell([NotNull] PFParser.MclassCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.extractspreparedCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExtractspreparedCell([NotNull] PFParser.ExtractspreparedCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.extractspreparedCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExtractspreparedCell([NotNull] PFParser.ExtractspreparedCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.typeCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeCell([NotNull] PFParser.TypeCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.typeCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeCell([NotNull] PFParser.TypeCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.acCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAcCell([NotNull] PFParser.AcCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.acCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAcCell([NotNull] PFParser.AcCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.dices"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDices([NotNull] PFParser.DicesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.dices"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDices([NotNull] PFParser.DicesContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.genderCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenderCell([NotNull] PFParser.GenderCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.genderCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenderCell([NotNull] PFParser.GenderCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.spelllikeabilitiesCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpelllikeabilitiesCell([NotNull] PFParser.SpelllikeabilitiesCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.spelllikeabilitiesCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpelllikeabilitiesCell([NotNull] PFParser.SpelllikeabilitiesCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.environmentCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnvironmentCell([NotNull] PFParser.EnvironmentCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.environmentCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnvironmentCell([NotNull] PFParser.EnvironmentCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.armorClassTouch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArmorClassTouch([NotNull] PFParser.ArmorClassTouchContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.armorClassTouch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArmorClassTouch([NotNull] PFParser.ArmorClassTouchContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.thassilonianspecializationCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThassilonianspecializationCell([NotNull] PFParser.ThassilonianspecializationCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.thassilonianspecializationCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThassilonianspecializationCell([NotNull] PFParser.ThassilonianspecializationCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.abilityscore_modsCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAbilityscore_modsCell([NotNull] PFParser.Abilityscore_modsCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.abilityscore_modsCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAbilityscore_modsCell([NotNull] PFParser.Abilityscore_modsCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.skillSpecial"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSkillSpecial([NotNull] PFParser.SkillSpecialContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.skillSpecial"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSkillSpecial([NotNull] PFParser.SkillSpecialContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.agecategoryCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAgecategoryCell([NotNull] PFParser.AgecategoryCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.agecategoryCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAgecategoryCell([NotNull] PFParser.AgecategoryCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterText([NotNull] PFParser.TextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitText([NotNull] PFParser.TextContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.meleeCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMeleeCell([NotNull] PFParser.MeleeCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.meleeCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMeleeCell([NotNull] PFParser.MeleeCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.posNegNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPosNegNumber([NotNull] PFParser.PosNegNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.posNegNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPosNegNumber([NotNull] PFParser.PosNegNumberContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.offensenoteCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOffensenoteCell([NotNull] PFParser.OffensenoteCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.offensenoteCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOffensenoteCell([NotNull] PFParser.OffensenoteCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.sizeCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSizeCell([NotNull] PFParser.SizeCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.sizeCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSizeCell([NotNull] PFParser.SizeCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.refCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRefCell([NotNull] PFParser.RefCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.refCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRefCell([NotNull] PFParser.RefCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.init"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInit([NotNull] PFParser.InitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.init"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInit([NotNull] PFParser.InitContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.sense"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSense([NotNull] PFParser.SenseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.sense"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSense([NotNull] PFParser.SenseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.resist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterResist([NotNull] PFParser.ResistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.resist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitResist([NotNull] PFParser.ResistContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.flyCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFlyCell([NotNull] PFParser.FlyCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.flyCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFlyCell([NotNull] PFParser.FlyCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.hpCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHpCell([NotNull] PFParser.HpCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.hpCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHpCell([NotNull] PFParser.HpCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModifier([NotNull] PFParser.ModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModifier([NotNull] PFParser.ModifierContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.cr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCr([NotNull] PFParser.CrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.cr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCr([NotNull] PFParser.CrContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.specialabilitiesCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecialabilitiesCell([NotNull] PFParser.SpecialabilitiesCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.specialabilitiesCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecialabilitiesCell([NotNull] PFParser.SpecialabilitiesCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.armorClassFlatFooted"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArmorClassFlatFooted([NotNull] PFParser.ArmorClassFlatFootedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.armorClassFlatFooted"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArmorClassFlatFooted([NotNull] PFParser.ArmorClassFlatFootedContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.immuneList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImmuneList([NotNull] PFParser.ImmuneListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.immuneList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImmuneList([NotNull] PFParser.ImmuneListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.languagesCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLanguagesCell([NotNull] PFParser.LanguagesCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.languagesCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLanguagesCell([NotNull] PFParser.LanguagesCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.xpCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterXpCell([NotNull] PFParser.XpCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.xpCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitXpCell([NotNull] PFParser.XpCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.diceSides"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDiceSides([NotNull] PFParser.DiceSidesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.diceSides"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDiceSides([NotNull] PFParser.DiceSidesContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.saves"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSaves([NotNull] PFParser.SavesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.saves"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSaves([NotNull] PFParser.SavesContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.landCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLandCell([NotNull] PFParser.LandCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.landCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLandCell([NotNull] PFParser.LandCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.willCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWillCell([NotNull] PFParser.WillCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.willCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWillCell([NotNull] PFParser.WillCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.organizationCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrganizationCell([NotNull] PFParser.OrganizationCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.organizationCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrganizationCell([NotNull] PFParser.OrganizationCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.climbCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClimbCell([NotNull] PFParser.ClimbCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.climbCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClimbCell([NotNull] PFParser.ClimbCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.save_modsCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSave_modsCell([NotNull] PFParser.Save_modsCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.save_modsCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSave_modsCell([NotNull] PFParser.Save_modsCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.descriptionCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDescriptionCell([NotNull] PFParser.DescriptionCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.descriptionCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDescriptionCell([NotNull] PFParser.DescriptionCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.auraCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAuraCell([NotNull] PFParser.AuraCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.auraCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAuraCell([NotNull] PFParser.AuraCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.speedCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpeedCell([NotNull] PFParser.SpeedCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.speedCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpeedCell([NotNull] PFParser.SpeedCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.burrowCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBurrowCell([NotNull] PFParser.BurrowCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.burrowCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBurrowCell([NotNull] PFParser.BurrowCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.templatesappliedCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemplatesappliedCell([NotNull] PFParser.TemplatesappliedCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.templatesappliedCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemplatesappliedCell([NotNull] PFParser.TemplatesappliedCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.dice"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDice([NotNull] PFParser.DiceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.dice"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDice([NotNull] PFParser.DiceContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.raceCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRaceCell([NotNull] PFParser.RaceCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.raceCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRaceCell([NotNull] PFParser.RaceCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterName([NotNull] PFParser.NameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitName([NotNull] PFParser.NameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.noteCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoteCell([NotNull] PFParser.NoteCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.noteCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoteCell([NotNull] PFParser.NoteCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.featsCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFeatsCell([NotNull] PFParser.FeatsCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.featsCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFeatsCell([NotNull] PFParser.FeatsCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.fortCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFortCell([NotNull] PFParser.FortCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.fortCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFortCell([NotNull] PFParser.FortCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.resistCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterResistCell([NotNull] PFParser.ResistCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.resistCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitResistCell([NotNull] PFParser.ResistCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.rangedCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRangedCell([NotNull] PFParser.RangedCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.rangedCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRangedCell([NotNull] PFParser.RangedCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.groupCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroupCell([NotNull] PFParser.GroupCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.groupCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroupCell([NotNull] PFParser.GroupCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.cmdCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmdCell([NotNull] PFParser.CmdCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.cmdCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmdCell([NotNull] PFParser.CmdCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.beforecombatCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBeforecombatCell([NotNull] PFParser.BeforecombatCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.beforecombatCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBeforecombatCell([NotNull] PFParser.BeforecombatCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.prohibitedschoolsCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProhibitedschoolsCell([NotNull] PFParser.ProhibitedschoolsCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.prohibitedschoolsCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProhibitedschoolsCell([NotNull] PFParser.ProhibitedschoolsCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.mclass"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMclass([NotNull] PFParser.MclassContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.mclass"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMclass([NotNull] PFParser.MclassContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.spelldomainsCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpelldomainsCell([NotNull] PFParser.SpelldomainsCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.spelldomainsCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpelldomainsCell([NotNull] PFParser.SpelldomainsCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.abilityscoresCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAbilityscoresCell([NotNull] PFParser.AbilityscoresCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.abilityscoresCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAbilityscoresCell([NotNull] PFParser.AbilityscoresCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.drList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDrList([NotNull] PFParser.DrListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.drList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDrList([NotNull] PFParser.DrListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.skillsCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSkillsCell([NotNull] PFParser.SkillsCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.skillsCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSkillsCell([NotNull] PFParser.SkillsCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.baseatkCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBaseatkCell([NotNull] PFParser.BaseatkCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.baseatkCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBaseatkCell([NotNull] PFParser.BaseatkCellContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.initCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitCell([NotNull] PFParser.InitCellContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.initCell"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitCell([NotNull] PFParser.InitCellContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
