//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/michiel/TabletopWitch/src/PreProcess/micfort.GMDroid.PF/Monster/PF.g4 by ANTLR 4.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="PFParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.3")]
[System.CLSCompliant(false)]
public interface IPFListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.gearCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGearCell([NotNull] PFParser.GearCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.gearCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGearCell([NotNull] PFParser.GearCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.skills"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSkills([NotNull] PFParser.SkillsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.skills"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSkills([NotNull] PFParser.SkillsContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.skillName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSkillName([NotNull] PFParser.SkillNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.skillName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSkillName([NotNull] PFParser.SkillNameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.restistList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRestistList([NotNull] PFParser.RestistListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.restistList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRestistList([NotNull] PFParser.RestistListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.vulnerabilityCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVulnerabilityCell([NotNull] PFParser.VulnerabilityCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.vulnerabilityCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVulnerabilityCell([NotNull] PFParser.VulnerabilityCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.reachCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReachCell([NotNull] PFParser.ReachCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.reachCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReachCell([NotNull] PFParser.ReachCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.immuneCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImmuneCell([NotNull] PFParser.ImmuneCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.immuneCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImmuneCell([NotNull] PFParser.ImmuneCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.characterflagCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCharacterflagCell([NotNull] PFParser.CharacterflagCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.characterflagCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCharacterflagCell([NotNull] PFParser.CharacterflagCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.alignmentCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlignmentCell([NotNull] PFParser.AlignmentCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.alignmentCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlignmentCell([NotNull] PFParser.AlignmentCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.ac_modsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAc_modsCell([NotNull] PFParser.Ac_modsCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.ac_modsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAc_modsCell([NotNull] PFParser.Ac_modsCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.spellspreparedCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpellspreparedCell([NotNull] PFParser.SpellspreparedCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.spellspreparedCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpellspreparedCell([NotNull] PFParser.SpellspreparedCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.mrCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMrCell([NotNull] PFParser.MrCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.mrCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMrCell([NotNull] PFParser.MrCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.othergearCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOthergearCell([NotNull] PFParser.OthergearCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.othergearCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOthergearCell([NotNull] PFParser.OthergearCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.diceCount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDiceCount([NotNull] PFParser.DiceCountContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.diceCount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDiceCount([NotNull] PFParser.DiceCountContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.traitsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTraitsCell([NotNull] PFParser.TraitsCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.traitsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTraitsCell([NotNull] PFParser.TraitsCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.srCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSrCell([NotNull] PFParser.SrCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.srCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSrCell([NotNull] PFParser.SrCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.treasureCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTreasureCell([NotNull] PFParser.TreasureCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.treasureCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTreasureCell([NotNull] PFParser.TreasureCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.nameCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameCell([NotNull] PFParser.NameCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.nameCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameCell([NotNull] PFParser.NameCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.armorClass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArmorClass([NotNull] PFParser.ArmorClassContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.armorClass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArmorClass([NotNull] PFParser.ArmorClassContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.monster"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMonster([NotNull] PFParser.MonsterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.monster"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMonster([NotNull] PFParser.MonsterContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.defensiveabilitiesCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefensiveabilitiesCell([NotNull] PFParser.DefensiveabilitiesCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.defensiveabilitiesCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefensiveabilitiesCell([NotNull] PFParser.DefensiveabilitiesCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.hp_modsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHp_modsCell([NotNull] PFParser.Hp_modsCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.hp_modsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHp_modsCell([NotNull] PFParser.Hp_modsCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.cell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCell([NotNull] PFParser.CellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.cell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCell([NotNull] PFParser.CellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.hd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHd([NotNull] PFParser.HdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.hd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHd([NotNull] PFParser.HdContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.weaknessesCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWeaknessesCell([NotNull] PFParser.WeaknessesCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.weaknessesCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWeaknessesCell([NotNull] PFParser.WeaknessesCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.drCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDrCell([NotNull] PFParser.DrCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.drCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDrCell([NotNull] PFParser.DrCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.sourceCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSourceCell([NotNull] PFParser.SourceCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.sourceCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSourceCell([NotNull] PFParser.SourceCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHeader([NotNull] PFParser.HeaderContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHeader([NotNull] PFParser.HeaderContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.spellsknownCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpellsknownCell([NotNull] PFParser.SpellsknownCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.spellsknownCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpellsknownCell([NotNull] PFParser.SpellsknownCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.crCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCrCell([NotNull] PFParser.CrCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.crCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCrCell([NotNull] PFParser.CrCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.pf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPf([NotNull] PFParser.PfContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.pf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPf([NotNull] PFParser.PfContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.skill"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSkill([NotNull] PFParser.SkillContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.skill"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSkill([NotNull] PFParser.SkillContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.savesRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSavesRef([NotNull] PFParser.SavesRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.savesRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSavesRef([NotNull] PFParser.SavesRefContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.companionflagCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompanionflagCell([NotNull] PFParser.CompanionflagCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.companionflagCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompanionflagCell([NotNull] PFParser.CompanionflagCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.sensesCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSensesCell([NotNull] PFParser.SensesCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.sensesCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSensesCell([NotNull] PFParser.SensesCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.focusedschoolCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFocusedschoolCell([NotNull] PFParser.FocusedschoolCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.focusedschoolCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFocusedschoolCell([NotNull] PFParser.FocusedschoolCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.swimCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwimCell([NotNull] PFParser.SwimCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.swimCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwimCell([NotNull] PFParser.SwimCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.senses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSenses([NotNull] PFParser.SensesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.senses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSenses([NotNull] PFParser.SensesContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.speed_modCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpeed_modCell([NotNull] PFParser.Speed_modCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.speed_modCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpeed_modCell([NotNull] PFParser.Speed_modCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.ac_modSpecial"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAc_modSpecial([NotNull] PFParser.Ac_modSpecialContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.ac_modSpecial"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAc_modSpecial([NotNull] PFParser.Ac_modSpecialContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] PFParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] PFParser.LineContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.bloodlineCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBloodlineCell([NotNull] PFParser.BloodlineCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.bloodlineCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBloodlineCell([NotNull] PFParser.BloodlineCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.basestatisticsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBasestatisticsCell([NotNull] PFParser.BasestatisticsCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.basestatisticsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBasestatisticsCell([NotNull] PFParser.BasestatisticsCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.distance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDistance([NotNull] PFParser.DistanceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.distance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDistance([NotNull] PFParser.DistanceContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.idCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdCell([NotNull] PFParser.IdCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.idCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdCell([NotNull] PFParser.IdCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.cmbCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmbCell([NotNull] PFParser.CmbCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.cmbCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmbCell([NotNull] PFParser.CmbCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.specialattacksCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpecialattacksCell([NotNull] PFParser.SpecialattacksCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.specialattacksCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpecialattacksCell([NotNull] PFParser.SpecialattacksCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.quotedText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuotedText([NotNull] PFParser.QuotedTextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.quotedText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuotedText([NotNull] PFParser.QuotedTextContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.linktextCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLinktextCell([NotNull] PFParser.LinktextCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.linktextCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLinktextCell([NotNull] PFParser.LinktextCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.duringcombatCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDuringcombatCell([NotNull] PFParser.DuringcombatCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.duringcombatCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDuringcombatCell([NotNull] PFParser.DuringcombatCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.hdCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHdCell([NotNull] PFParser.HdCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.hdCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHdCell([NotNull] PFParser.HdCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.spaceCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpaceCell([NotNull] PFParser.SpaceCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.spaceCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpaceCell([NotNull] PFParser.SpaceCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.companionfamiliarlinkCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompanionfamiliarlinkCell([NotNull] PFParser.CompanionfamiliarlinkCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.companionfamiliarlinkCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompanionfamiliarlinkCell([NotNull] PFParser.CompanionfamiliarlinkCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.mythicCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMythicCell([NotNull] PFParser.MythicCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.mythicCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMythicCell([NotNull] PFParser.MythicCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.ac_mod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAc_mod([NotNull] PFParser.Ac_modContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.ac_mod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAc_mod([NotNull] PFParser.Ac_modContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.dr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDr([NotNull] PFParser.DrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.dr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDr([NotNull] PFParser.DrContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.classarchetypesCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassarchetypesCell([NotNull] PFParser.ClassarchetypesCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.classarchetypesCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassarchetypesCell([NotNull] PFParser.ClassarchetypesCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.istemplateCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIstemplateCell([NotNull] PFParser.IstemplateCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.istemplateCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIstemplateCell([NotNull] PFParser.IstemplateCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.monstersourceCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMonstersourceCell([NotNull] PFParser.MonstersourceCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.monstersourceCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMonstersourceCell([NotNull] PFParser.MonstersourceCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.mysteryCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMysteryCell([NotNull] PFParser.MysteryCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.mysteryCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMysteryCell([NotNull] PFParser.MysteryCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.immune"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImmune([NotNull] PFParser.ImmuneContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.immune"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImmune([NotNull] PFParser.ImmuneContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.variantCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariantCell([NotNull] PFParser.VariantCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.variantCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariantCell([NotNull] PFParser.VariantCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.fulltextCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFulltextCell([NotNull] PFParser.FulltextCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.fulltextCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFulltextCell([NotNull] PFParser.FulltextCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.uniquemonsterCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUniquemonsterCell([NotNull] PFParser.UniquemonsterCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.uniquemonsterCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUniquemonsterCell([NotNull] PFParser.UniquemonsterCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.savesWill"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSavesWill([NotNull] PFParser.SavesWillContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.savesWill"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSavesWill([NotNull] PFParser.SavesWillContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.racialmodsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRacialmodsCell([NotNull] PFParser.RacialmodsCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.racialmodsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRacialmodsCell([NotNull] PFParser.RacialmodsCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.savesFort"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSavesFort([NotNull] PFParser.SavesFortContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.savesFort"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSavesFort([NotNull] PFParser.SavesFortContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.ac_mods"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAc_mods([NotNull] PFParser.Ac_modsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.ac_mods"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAc_mods([NotNull] PFParser.Ac_modsContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.alternatenameformCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlternatenameformCell([NotNull] PFParser.AlternatenameformCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.alternatenameformCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlternatenameformCell([NotNull] PFParser.AlternatenameformCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.subtypeCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubtypeCell([NotNull] PFParser.SubtypeCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.subtypeCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubtypeCell([NotNull] PFParser.SubtypeCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.mtCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMtCell([NotNull] PFParser.MtCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.mtCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMtCell([NotNull] PFParser.MtCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.description_visualCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDescription_visualCell([NotNull] PFParser.Description_visualCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.description_visualCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDescription_visualCell([NotNull] PFParser.Description_visualCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.patronCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPatronCell([NotNull] PFParser.PatronCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.patronCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPatronCell([NotNull] PFParser.PatronCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.mclassName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMclassName([NotNull] PFParser.MclassNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.mclassName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMclassName([NotNull] PFParser.MclassNameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.moraleCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMoraleCell([NotNull] PFParser.MoraleCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.moraleCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMoraleCell([NotNull] PFParser.MoraleCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.savesCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSavesCell([NotNull] PFParser.SavesCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.savesCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSavesCell([NotNull] PFParser.SavesCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.sqCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSqCell([NotNull] PFParser.SqCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.sqCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSqCell([NotNull] PFParser.SqCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.mclassCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMclassCell([NotNull] PFParser.MclassCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.mclassCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMclassCell([NotNull] PFParser.MclassCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.extractspreparedCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtractspreparedCell([NotNull] PFParser.ExtractspreparedCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.extractspreparedCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtractspreparedCell([NotNull] PFParser.ExtractspreparedCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.typeCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeCell([NotNull] PFParser.TypeCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.typeCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeCell([NotNull] PFParser.TypeCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.acCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAcCell([NotNull] PFParser.AcCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.acCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAcCell([NotNull] PFParser.AcCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.dices"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDices([NotNull] PFParser.DicesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.dices"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDices([NotNull] PFParser.DicesContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.genderCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenderCell([NotNull] PFParser.GenderCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.genderCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenderCell([NotNull] PFParser.GenderCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.spelllikeabilitiesCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpelllikeabilitiesCell([NotNull] PFParser.SpelllikeabilitiesCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.spelllikeabilitiesCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpelllikeabilitiesCell([NotNull] PFParser.SpelllikeabilitiesCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.environmentCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnvironmentCell([NotNull] PFParser.EnvironmentCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.environmentCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnvironmentCell([NotNull] PFParser.EnvironmentCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.armorClassTouch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArmorClassTouch([NotNull] PFParser.ArmorClassTouchContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.armorClassTouch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArmorClassTouch([NotNull] PFParser.ArmorClassTouchContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.thassilonianspecializationCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThassilonianspecializationCell([NotNull] PFParser.ThassilonianspecializationCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.thassilonianspecializationCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThassilonianspecializationCell([NotNull] PFParser.ThassilonianspecializationCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.abilityscore_modsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAbilityscore_modsCell([NotNull] PFParser.Abilityscore_modsCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.abilityscore_modsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAbilityscore_modsCell([NotNull] PFParser.Abilityscore_modsCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.skillSpecial"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSkillSpecial([NotNull] PFParser.SkillSpecialContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.skillSpecial"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSkillSpecial([NotNull] PFParser.SkillSpecialContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.agecategoryCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAgecategoryCell([NotNull] PFParser.AgecategoryCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.agecategoryCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAgecategoryCell([NotNull] PFParser.AgecategoryCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterText([NotNull] PFParser.TextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitText([NotNull] PFParser.TextContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.meleeCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMeleeCell([NotNull] PFParser.MeleeCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.meleeCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMeleeCell([NotNull] PFParser.MeleeCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.posNegNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPosNegNumber([NotNull] PFParser.PosNegNumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.posNegNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPosNegNumber([NotNull] PFParser.PosNegNumberContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.offensenoteCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOffensenoteCell([NotNull] PFParser.OffensenoteCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.offensenoteCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOffensenoteCell([NotNull] PFParser.OffensenoteCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.sizeCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSizeCell([NotNull] PFParser.SizeCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.sizeCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSizeCell([NotNull] PFParser.SizeCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.refCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRefCell([NotNull] PFParser.RefCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.refCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRefCell([NotNull] PFParser.RefCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInit([NotNull] PFParser.InitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInit([NotNull] PFParser.InitContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.sense"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSense([NotNull] PFParser.SenseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.sense"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSense([NotNull] PFParser.SenseContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.resist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterResist([NotNull] PFParser.ResistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.resist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitResist([NotNull] PFParser.ResistContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.flyCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFlyCell([NotNull] PFParser.FlyCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.flyCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFlyCell([NotNull] PFParser.FlyCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.hpCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHpCell([NotNull] PFParser.HpCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.hpCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHpCell([NotNull] PFParser.HpCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModifier([NotNull] PFParser.ModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModifier([NotNull] PFParser.ModifierContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.cr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCr([NotNull] PFParser.CrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.cr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCr([NotNull] PFParser.CrContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.specialabilitiesCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpecialabilitiesCell([NotNull] PFParser.SpecialabilitiesCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.specialabilitiesCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpecialabilitiesCell([NotNull] PFParser.SpecialabilitiesCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.armorClassFlatFooted"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArmorClassFlatFooted([NotNull] PFParser.ArmorClassFlatFootedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.armorClassFlatFooted"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArmorClassFlatFooted([NotNull] PFParser.ArmorClassFlatFootedContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.immuneList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImmuneList([NotNull] PFParser.ImmuneListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.immuneList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImmuneList([NotNull] PFParser.ImmuneListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.languagesCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLanguagesCell([NotNull] PFParser.LanguagesCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.languagesCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLanguagesCell([NotNull] PFParser.LanguagesCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.xpCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterXpCell([NotNull] PFParser.XpCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.xpCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitXpCell([NotNull] PFParser.XpCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.diceSides"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDiceSides([NotNull] PFParser.DiceSidesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.diceSides"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDiceSides([NotNull] PFParser.DiceSidesContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.saves"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSaves([NotNull] PFParser.SavesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.saves"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSaves([NotNull] PFParser.SavesContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.landCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLandCell([NotNull] PFParser.LandCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.landCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLandCell([NotNull] PFParser.LandCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.willCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWillCell([NotNull] PFParser.WillCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.willCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWillCell([NotNull] PFParser.WillCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.organizationCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrganizationCell([NotNull] PFParser.OrganizationCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.organizationCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrganizationCell([NotNull] PFParser.OrganizationCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.climbCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClimbCell([NotNull] PFParser.ClimbCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.climbCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClimbCell([NotNull] PFParser.ClimbCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.save_modsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSave_modsCell([NotNull] PFParser.Save_modsCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.save_modsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSave_modsCell([NotNull] PFParser.Save_modsCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.descriptionCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDescriptionCell([NotNull] PFParser.DescriptionCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.descriptionCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDescriptionCell([NotNull] PFParser.DescriptionCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.auraCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAuraCell([NotNull] PFParser.AuraCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.auraCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAuraCell([NotNull] PFParser.AuraCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.speedCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpeedCell([NotNull] PFParser.SpeedCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.speedCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpeedCell([NotNull] PFParser.SpeedCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.burrowCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBurrowCell([NotNull] PFParser.BurrowCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.burrowCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBurrowCell([NotNull] PFParser.BurrowCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.templatesappliedCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplatesappliedCell([NotNull] PFParser.TemplatesappliedCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.templatesappliedCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplatesappliedCell([NotNull] PFParser.TemplatesappliedCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.dice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDice([NotNull] PFParser.DiceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.dice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDice([NotNull] PFParser.DiceContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.raceCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRaceCell([NotNull] PFParser.RaceCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.raceCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRaceCell([NotNull] PFParser.RaceCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterName([NotNull] PFParser.NameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitName([NotNull] PFParser.NameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.noteCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoteCell([NotNull] PFParser.NoteCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.noteCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoteCell([NotNull] PFParser.NoteCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.featsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFeatsCell([NotNull] PFParser.FeatsCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.featsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFeatsCell([NotNull] PFParser.FeatsCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.fortCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFortCell([NotNull] PFParser.FortCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.fortCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFortCell([NotNull] PFParser.FortCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.resistCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterResistCell([NotNull] PFParser.ResistCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.resistCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitResistCell([NotNull] PFParser.ResistCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.rangedCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRangedCell([NotNull] PFParser.RangedCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.rangedCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRangedCell([NotNull] PFParser.RangedCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.groupCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroupCell([NotNull] PFParser.GroupCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.groupCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroupCell([NotNull] PFParser.GroupCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.cmdCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmdCell([NotNull] PFParser.CmdCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.cmdCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmdCell([NotNull] PFParser.CmdCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.beforecombatCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBeforecombatCell([NotNull] PFParser.BeforecombatCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.beforecombatCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBeforecombatCell([NotNull] PFParser.BeforecombatCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.prohibitedschoolsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProhibitedschoolsCell([NotNull] PFParser.ProhibitedschoolsCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.prohibitedschoolsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProhibitedschoolsCell([NotNull] PFParser.ProhibitedschoolsCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.mclass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMclass([NotNull] PFParser.MclassContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.mclass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMclass([NotNull] PFParser.MclassContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.spelldomainsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpelldomainsCell([NotNull] PFParser.SpelldomainsCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.spelldomainsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpelldomainsCell([NotNull] PFParser.SpelldomainsCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.abilityscoresCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAbilityscoresCell([NotNull] PFParser.AbilityscoresCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.abilityscoresCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAbilityscoresCell([NotNull] PFParser.AbilityscoresCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.drList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDrList([NotNull] PFParser.DrListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.drList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDrList([NotNull] PFParser.DrListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.skillsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSkillsCell([NotNull] PFParser.SkillsCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.skillsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSkillsCell([NotNull] PFParser.SkillsCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.baseatkCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBaseatkCell([NotNull] PFParser.BaseatkCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.baseatkCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBaseatkCell([NotNull] PFParser.BaseatkCellContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="PFParser.initCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitCell([NotNull] PFParser.InitCellContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PFParser.initCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitCell([NotNull] PFParser.InitCellContext context);
}
