//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/michiel/TabletopWitch/src/PreProcess/micfort.GMDroid.PF/Monster/PF.g4 by ANTLR 4.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="PFParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.3")]
[System.CLSCompliant(false)]
public interface IPFVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.gearCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGearCell([NotNull] PFParser.GearCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.skills"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSkills([NotNull] PFParser.SkillsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.skillName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSkillName([NotNull] PFParser.SkillNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.restistList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRestistList([NotNull] PFParser.RestistListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.vulnerabilityCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVulnerabilityCell([NotNull] PFParser.VulnerabilityCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.reachCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReachCell([NotNull] PFParser.ReachCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.immuneCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImmuneCell([NotNull] PFParser.ImmuneCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.characterflagCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharacterflagCell([NotNull] PFParser.CharacterflagCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.alignmentCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlignmentCell([NotNull] PFParser.AlignmentCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.ac_modsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAc_modsCell([NotNull] PFParser.Ac_modsCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.spellspreparedCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpellspreparedCell([NotNull] PFParser.SpellspreparedCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.mrCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMrCell([NotNull] PFParser.MrCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.othergearCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOthergearCell([NotNull] PFParser.OthergearCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.diceCount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDiceCount([NotNull] PFParser.DiceCountContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.traitsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTraitsCell([NotNull] PFParser.TraitsCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.srCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSrCell([NotNull] PFParser.SrCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.treasureCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTreasureCell([NotNull] PFParser.TreasureCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.nameCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNameCell([NotNull] PFParser.NameCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.armorClass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArmorClass([NotNull] PFParser.ArmorClassContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.monster"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonster([NotNull] PFParser.MonsterContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.defensiveabilitiesCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefensiveabilitiesCell([NotNull] PFParser.DefensiveabilitiesCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.hp_modsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHp_modsCell([NotNull] PFParser.Hp_modsCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.cell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCell([NotNull] PFParser.CellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.hd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHd([NotNull] PFParser.HdContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.weaknessesCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWeaknessesCell([NotNull] PFParser.WeaknessesCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.drCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrCell([NotNull] PFParser.DrCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.sourceCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSourceCell([NotNull] PFParser.SourceCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHeader([NotNull] PFParser.HeaderContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.spellsknownCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpellsknownCell([NotNull] PFParser.SpellsknownCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.crCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCrCell([NotNull] PFParser.CrCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.pf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPf([NotNull] PFParser.PfContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.skill"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSkill([NotNull] PFParser.SkillContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.savesRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSavesRef([NotNull] PFParser.SavesRefContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.companionflagCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompanionflagCell([NotNull] PFParser.CompanionflagCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.sensesCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSensesCell([NotNull] PFParser.SensesCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.focusedschoolCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFocusedschoolCell([NotNull] PFParser.FocusedschoolCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.swimCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwimCell([NotNull] PFParser.SwimCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.senses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSenses([NotNull] PFParser.SensesContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.speed_modCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpeed_modCell([NotNull] PFParser.Speed_modCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.ac_modSpecial"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAc_modSpecial([NotNull] PFParser.Ac_modSpecialContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine([NotNull] PFParser.LineContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.bloodlineCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBloodlineCell([NotNull] PFParser.BloodlineCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.basestatisticsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBasestatisticsCell([NotNull] PFParser.BasestatisticsCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.distance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDistance([NotNull] PFParser.DistanceContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.idCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdCell([NotNull] PFParser.IdCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.cmbCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCmbCell([NotNull] PFParser.CmbCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.specialattacksCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecialattacksCell([NotNull] PFParser.SpecialattacksCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.quotedText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuotedText([NotNull] PFParser.QuotedTextContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.linktextCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLinktextCell([NotNull] PFParser.LinktextCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.duringcombatCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDuringcombatCell([NotNull] PFParser.DuringcombatCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.hdCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHdCell([NotNull] PFParser.HdCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.spaceCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpaceCell([NotNull] PFParser.SpaceCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.companionfamiliarlinkCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompanionfamiliarlinkCell([NotNull] PFParser.CompanionfamiliarlinkCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.mythicCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMythicCell([NotNull] PFParser.MythicCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.ac_mod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAc_mod([NotNull] PFParser.Ac_modContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.dr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDr([NotNull] PFParser.DrContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.classarchetypesCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassarchetypesCell([NotNull] PFParser.ClassarchetypesCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.istemplateCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIstemplateCell([NotNull] PFParser.IstemplateCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.monstersourceCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMonstersourceCell([NotNull] PFParser.MonstersourceCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.mysteryCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMysteryCell([NotNull] PFParser.MysteryCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.immune"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImmune([NotNull] PFParser.ImmuneContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.variantCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariantCell([NotNull] PFParser.VariantCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.fulltextCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFulltextCell([NotNull] PFParser.FulltextCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.uniquemonsterCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUniquemonsterCell([NotNull] PFParser.UniquemonsterCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.savesWill"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSavesWill([NotNull] PFParser.SavesWillContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.racialmodsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRacialmodsCell([NotNull] PFParser.RacialmodsCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.savesFort"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSavesFort([NotNull] PFParser.SavesFortContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.ac_mods"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAc_mods([NotNull] PFParser.Ac_modsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.alternatenameformCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlternatenameformCell([NotNull] PFParser.AlternatenameformCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.subtypeCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubtypeCell([NotNull] PFParser.SubtypeCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.mtCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMtCell([NotNull] PFParser.MtCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.description_visualCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDescription_visualCell([NotNull] PFParser.Description_visualCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.patronCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPatronCell([NotNull] PFParser.PatronCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.mclassName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMclassName([NotNull] PFParser.MclassNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.moraleCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMoraleCell([NotNull] PFParser.MoraleCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.savesCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSavesCell([NotNull] PFParser.SavesCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.sqCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSqCell([NotNull] PFParser.SqCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.mclassCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMclassCell([NotNull] PFParser.MclassCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.extractspreparedCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtractspreparedCell([NotNull] PFParser.ExtractspreparedCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.typeCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeCell([NotNull] PFParser.TypeCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.acCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAcCell([NotNull] PFParser.AcCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.dices"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDices([NotNull] PFParser.DicesContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.genderCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenderCell([NotNull] PFParser.GenderCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.spelllikeabilitiesCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpelllikeabilitiesCell([NotNull] PFParser.SpelllikeabilitiesCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.environmentCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnvironmentCell([NotNull] PFParser.EnvironmentCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.armorClassTouch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArmorClassTouch([NotNull] PFParser.ArmorClassTouchContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.thassilonianspecializationCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThassilonianspecializationCell([NotNull] PFParser.ThassilonianspecializationCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.abilityscore_modsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbilityscore_modsCell([NotNull] PFParser.Abilityscore_modsCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.skillSpecial"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSkillSpecial([NotNull] PFParser.SkillSpecialContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.agecategoryCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAgecategoryCell([NotNull] PFParser.AgecategoryCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitText([NotNull] PFParser.TextContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.meleeCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMeleeCell([NotNull] PFParser.MeleeCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.posNegNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPosNegNumber([NotNull] PFParser.PosNegNumberContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.offensenoteCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOffensenoteCell([NotNull] PFParser.OffensenoteCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.sizeCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSizeCell([NotNull] PFParser.SizeCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.refCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRefCell([NotNull] PFParser.RefCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInit([NotNull] PFParser.InitContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.sense"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSense([NotNull] PFParser.SenseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.resist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResist([NotNull] PFParser.ResistContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.flyCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFlyCell([NotNull] PFParser.FlyCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.hpCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHpCell([NotNull] PFParser.HpCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModifier([NotNull] PFParser.ModifierContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.cr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCr([NotNull] PFParser.CrContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.specialabilitiesCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecialabilitiesCell([NotNull] PFParser.SpecialabilitiesCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.armorClassFlatFooted"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArmorClassFlatFooted([NotNull] PFParser.ArmorClassFlatFootedContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.immuneList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImmuneList([NotNull] PFParser.ImmuneListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.languagesCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLanguagesCell([NotNull] PFParser.LanguagesCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.xpCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXpCell([NotNull] PFParser.XpCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.diceSides"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDiceSides([NotNull] PFParser.DiceSidesContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.saves"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSaves([NotNull] PFParser.SavesContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.landCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLandCell([NotNull] PFParser.LandCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.willCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWillCell([NotNull] PFParser.WillCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.organizationCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrganizationCell([NotNull] PFParser.OrganizationCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.climbCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClimbCell([NotNull] PFParser.ClimbCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.save_modsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSave_modsCell([NotNull] PFParser.Save_modsCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.descriptionCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDescriptionCell([NotNull] PFParser.DescriptionCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.auraCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAuraCell([NotNull] PFParser.AuraCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.speedCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpeedCell([NotNull] PFParser.SpeedCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.burrowCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBurrowCell([NotNull] PFParser.BurrowCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.templatesappliedCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplatesappliedCell([NotNull] PFParser.TemplatesappliedCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.dice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDice([NotNull] PFParser.DiceContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.raceCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRaceCell([NotNull] PFParser.RaceCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName([NotNull] PFParser.NameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.noteCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoteCell([NotNull] PFParser.NoteCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.featsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFeatsCell([NotNull] PFParser.FeatsCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.fortCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFortCell([NotNull] PFParser.FortCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.resistCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResistCell([NotNull] PFParser.ResistCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.rangedCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRangedCell([NotNull] PFParser.RangedCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.groupCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroupCell([NotNull] PFParser.GroupCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.cmdCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCmdCell([NotNull] PFParser.CmdCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.beforecombatCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBeforecombatCell([NotNull] PFParser.BeforecombatCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.prohibitedschoolsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProhibitedschoolsCell([NotNull] PFParser.ProhibitedschoolsCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.mclass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMclass([NotNull] PFParser.MclassContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.spelldomainsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpelldomainsCell([NotNull] PFParser.SpelldomainsCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.abilityscoresCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbilityscoresCell([NotNull] PFParser.AbilityscoresCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.drList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrList([NotNull] PFParser.DrListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.skillsCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSkillsCell([NotNull] PFParser.SkillsCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.baseatkCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseatkCell([NotNull] PFParser.BaseatkCellContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="PFParser.initCell"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitCell([NotNull] PFParser.InitCellContext context);
}
